# Generated by Django 2.0 on 2018-03-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowmedy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
