# Generated by Django 2.0 on 2018-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('causes', models.TextField(default='')),
                ('symptoms', models.TextField(blank='')),
                ('diagnosis', models.TextField(blank='')),
                ('complications', models.TextField(blank='')),
                ('medicine', models.TextField(blank='')),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
            ],
        ),
    ]
